### ISSUE TITLE
Issue with this js file .. setquestion function is defined in js 

### ISSUE THREAD

**Issue by nk8291** [luiscantero/power-bi-qna-web-api#1]
Thank you making this API utility, really helpful.. I am trying to configure my parameters in config.js and trying to execute the js file, but it's throwing an error saying setfunction is not available in js file

**Comment by nk8291** [comment]
also it is not downloading/ taking Screenshot of the rendered chart as image

**Comment by nk8291** [comment]
@luiscantero

**Comment by luiscantero** [comment]
This code is 5-6 years old. I'm not up-to-date anymore and cannot help.
